language: go
env:
  DOCKER_COMPOSE_VERSION: 1.18.0
go:
  - tip
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - go get github.com/mattn/goveralls
  - sudo cp $GOPATH/bin/goveralls /usr/bin/goveralls
  - echo $PATH
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/env
  - ./startdb.sh
  - cd $TRAVIS_BUILD_DIR
  - docker ps
  - go version
before_script:
  - go install ./vendor/github.com/...
script: goveralls -service=travis-ci