version: '3'

services:  
  couchdb:
    container_name: couchdb
    image: library/couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      app_net:
        ipv4_address: 172.16.239.2
  goserver:
    container_name: goserver
    image: library/golang:alpine
    environment:
      - PROJECTPATH=/go/src/ffxbluetest
    working_dir: /go/src/ffxbluetest
    entrypoint:
      - /bin/sh
      - -c
      - |
        go build -o server
        ./server
    volumes:
      - ../:/go/src/ffxbluetest
      - ../vendor/github.com/:/go/src/github.com/
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.16.239.3
    depends_on:
      - couchdb
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
